

COMMON_DIR = ../../common/

build:
	g++ Problem1.cpp -I$(COMMON_DIR) $(COMMON_DIR)Coons.o $(COMMON_DIR)formatting.o $(COMMON_DIR)Bezier_algs.o \
	-o Problem1 -g -larmadillo

clean:

	rm -f Problem1 *~ *#
