

COMMON_DIR = ../../common/

build:
	g++ Problem8.cpp -I$(COMMON_DIR) $(COMMON_DIR)BSpline_algs.o $(COMMON_DIR)formatting.o $(COMMON_DIR)Bezier_algs.o \
	-o Problem8 -g -larmadillo

clean:

	rm -f Problem8 *~ *#
