
build: formatting.o Bezier_algs.o BSpline_algs.o Coons.o Ferguson.o

formatting.o:
	g++ -c formatting.cpp -g -o formatting.o

Bezier_algs.o:
	g++ -c Bezier_algs.cpp -g -o Bezier_algs.o

BSpline_algs.o:
	g++ -c BSpline_algs.cpp -g -o BSpline_algs.o

Coons.o:
	g++ -c Coons.cpp -g -o Coons.o

Ferguson.o:
	g++ -c Ferguson.cpp -g -o Ferguson.o

clean:
	rm -f *.o *~
