
build: formatting.o Bezier_algs.o BSpline_algs.o

formatting.o:
	g++ -c formatting.cpp -o formatting.o

Bezier_algs.o:
	g++ -c Bezier_algs.cpp -o Bezier_algs.o

BSpline_algs.o:
	g++ -c BSpline_algs.cpp -o BSpline_algs.o

clean:
	rm -f *.o *~
