

COMMON_DIR = ../../common/

build:
	g++ Problem2.cpp -I$(COMMON_DIR) $(COMMON_DIR)Ferguson.o $(COMMON_DIR)Coons.o $(COMMON_DIR)BSpline_algs.o $(COMMON_DIR)formatting.o $(COMMON_DIR)Bezier_algs.o \
	-o Problem2 -g -larmadillo

clean:

	rm -f Problem2 *~ *#
