

COMMON_DIR = ../../common/

build:
	g++ Problem6.cpp -I$(COMMON_DIR) $(COMMON_DIR)BSpline_algs.o $(COMMON_DIR)formatting.o $(COMMON_DIR)Bezier_algs.o \
	-o Problem6 -g -larmadillo

clean:

	rm -f Problem5 *~ *#
